### ISSUE TITLE
go.mod release

### ISSUE THREAD

**Issue by WhoSoup** [FactomProject/factom#142]
Version # proposal: v0.4.0 (currently we're at v0.3.6)

I added most of the sensible open PRs and issues to the the board. Most of these are ready to be reviewed but some still need more work, mainly the go.mod one. 

There are two PRs that need special attention:
* https://github.com/FactomProject/factom/pull/135 The whitelist feature will also need a new release of factom-walletd (https://github.com/FactomProject/factom-walletd/pull/85) to enable the feature for users
* https://github.com/FactomProject/factom/pull/137 the optional raw-data feature will need the factomd api counterpart integrated

We should decide if we should include these now and they just aren't useful until their counterparts are enabled, or wait until integration is done on the other side and then make another release.

**Comment by PaulBernier** [comment]
Thanks for putting this together.
I propose we make all those PR against develop for now, that will be our working branch for the time being.
I would lean towards postponing those 2 features for now, like for Wax, my idea is to try to wrap up things and get a release out, one we are confident to be able to quickly iterate over in the future. Let me know if you like that approach or not.

**Comment by PaulBernier** [comment]
Also I suggest using 'squash and merge' when merging PRs

**Comment by PaulBernier** [comment]
Released
