### ISSUE TITLE
factom.SignData() - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by StarNeit** [FactomProject/factom#150]
Recently, we tried to use `factom.SignData()` to make a signature for the project.

But, it returned runtime panic error.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1376423]
```
 
Here is factom version we used:
```
github.com/FactomProject/factom v0.3.6-0.20200826003247-4751d0f52dda
github.com/FactomProject/factomd v6.3.2+incompatible
```

Is there any known issue why this runtime panic error is happening when try to sign data to generate signature?

Here is code snipped we used.
```
func (spr *StakingPriceRecord) CreateSPREntry() (*factom.Entry, error) {
	e := new(factom.Entry)
	e.ChainID = hex.EncodeToString(base58.Decode(spr.SPRChainID))

	rcd, err := common.ConvertFCTtoRaw(spr.CoinbaseAddress)
	if err != nil {
		return nil, err
	}

	e.Content, err = spr.SafeMarshal()
	if err != nil {
		return nil, err
	}

	signature, errS := factom.SignData(spr.CoinbaseAddress, e.Content)
	if errS != nil {
		return nil, err
	}
	pubKey := signature.PubKey
	sign := signature.Signature
	signData := append(pubKey, sign...)

	e.ExtIDs = [][]byte{{spr.Version}, rcd, signData}

	return e, nil
}
```
factom.SignData() returns panic error now.

@PaulSnow , @WhoSoup 

Thank you in advance.

**Comment by WhoSoup** [comment]
> But, it returned runtime panic error.
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1376423]
> ```

Can you provide the full error? This line alone unfortunately doesn't tell us much. What values did you have for address/data that caused it to panic? I haven't been able to reproduce this error.

**Comment by PaulBernier** [comment]
Given there was no reply I am resolving this. Moreover this error is from a fork of the official factom library that is not supported here.
