### ISSUE TITLE
Problem install Factom

### ISSUE THREAD

**Issue by erotundo** [FactomProject/factom#27]
Hi!

Factom it's available for run with go compiler 1.8? The installation process give me a error when i try to run factom in linux server

```
$ factomd
//////////////////////// Copyright 2017 Factom Foundation
//////////////////////// Use of this source code is governed by the MIT
//////////////////////// license that can be found in the LICENSE file.
Go compiler version: go1.8
Using build: 701f2cca5ed1f71771a36f8e0386f707106190fb
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
!!! !!! !!! ERROR: unsupported compiler version !!! !!! !!!
```

After view this error i try to install using all.sh script but i got this another error

```
[INFO]  Replacing existing vendor dependencies
./all.sh: line 99: cd: addservermessage: No such file or directory
Compiling:  addservermessage
[ERROR] Failed to find glide.yaml file in directory tree: Cannot resolve parent of /
can't load package: package github.com/FactomProject: no buildable Go source files in /home/ubuntu/go/src/github.com/FactomProject
```

Regards

ER

**Comment by carryforward** [comment]
good catch.  The master branch of the current version was released before we did much testing on 1.8.

We have since done more testing, and 1.8 is ok.
get this branch to get the master code without this restriction: https://github.com/FactomProject/factomd/tree/1.8

The next version will support 1.8 when it gets pushed to master.

**Comment by erotundo** [comment]
Hi!! It's me again.

So finally the factom project runs and this is great.

There is something that I do not really understand and that is why I ask the following question.
Having the blockchain running on a dedicated server, can I use the client inside a mobile device to upload transactions to this server ?, ie it loads information but in a way that is encrypted from an external device and that someone (with permission To decrypt this information. Is this possible?. Excuse me if my question is trivial but first time I work with this form

ER

**Comment by carryforward** [comment]
I'm glad to hear it is working in this application.

sure, this is what the tax demo does.  it encrypts the data before it is handed to factomd.  only the people with the RSA private key can decrypt the data.  The encrypted data would be in the payload of the Entry.  The entry would be put in the factomd running on your mobile device.

The thing about cryptography is that there is no "permission" per se.  Someone either has private key or they don't.

**Comment by erotundo** [comment]
Hi!!!

Thanks for your answer, so related than this, i need to use commit-chain/ to send the encrypted information to my server with factom running right? and the result of this it's the validation of commited process. In the example the step of "Post to Factom"

Regards

ER

**Comment by erotundo** [comment]
Hello!

If you please guide me to use a remote post into blockchain the information

I posted a another comment but i don't receive answer related that

Regards

ER

**Comment by gelijie** [comment]
i do not know how to install Factom on my Computer
