### ISSUE TITLE
Transactions take a long time to load

### ISSUE THREAD

**Issue by WhoSoup** [FactomProject/factom#85]
I was tasked to investigate why the "Transactions" page is fairly slow to load, and I tracked down the error to the `GetTXRange` function:
https://github.com/FactomProject/factom/blob/27c6cd7271cf79e69d9db86d0d9498f9bc9d1a59/wallet/txdatabase.go#L207-L216

In order to get a range of transactions by height, the code first gets every single transaction via `txs, err := db.GetAllTXs()` (by scanning through all 170k+ Factoid Blocks) and then loops through all transactions to filter out the ones with the desirable height. This is obviously not very efficient and caused the function `GetRelatedTransactions` to perform very poorly, taking an average of ~5seconds to execute on my pc.

This function locks a mutex.
https://github.com/FactomProject/enterprise-wallet/blob/7819099c274a1bedaa9d677371c0b29079931f2a/wallet/walletDB.go#L390-L391

The mutex remains locked as long as the function runs in the background and it's automatically scheduled to execute every 10 seconds, which prevented the "Transactions" page from loading as it waited for that mutex to be released.

This can be fixed by rewriting the `GetTxRange` function to only cycle from the head down to the desired height and grabbing the related transactions instead of all 170k+ factoid blocks, which drove down execution time to ~250ms on my pc.

Proposed fix: https://github.com/WhoSoup/factom/commit/e0e9e5dfe17178ef0f3b7186a9a3a29a8a5d9478

(note: the new code is substantially copy/pasted from `GetAllTxs`)

**Comment by Cahl-Dee** [comment]
This is addressed in #88 and is pulled over to EW in: https://github.com/FactomProject/enterprise-wallet/pull/35 

Therefore closing this.
